version: "3"
services:
  digdag:
    build: .
    container_name: digdag_ecs
    ports:
      - "5000:65432"
    depends_on:
      - "postgresql"
    environment:
      ENVRONMENT: develop
      AWS_ACCESS_KEY: "<Your AWS Access Key>"
      AWS_SECRET_KEY: "<Your AWS Secret Key>"
      AWS_S3_EXAMPLE_BUCKET: "<S3 Bucket name>"
      AWS_S3_EXAMPLE_PATH: "<S3 Bucket path>"
  postgresql:
    image: postgres:11
    container_name: postgres_ecs
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

