version: "3"
services:
  digdag:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/digdag-ecs:1.0
    container_name: digdag_ecs
    ports:
      - "65432:65432"
    environment:
      ENVRONMENT: production
      AWS_ACCESS_KEY: "<Your AWS Access Key>"
      AWS_SECRET_KEY: "<Your AWS Secret Key>"
      AWS_S3_EXAMPLE_BUCKET: "<S3 Bucket name>"
      AWS_S3_EXAMPLE_PATH: "<S3 Bucket path>"
    logging:
      driver: awslogs
      options:
        awslogs-group: digdag-ecs
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: digdag-ecs

